ALTER TABLE fornecedores CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE contatos CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE usuario CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE pgtos CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE pgtos_parcela CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE pgtos_quitacao CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE setores CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE contas CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

alter DATABASE `webfinancas` /*!40100 DEFAULT CHARACTER SET utf8 */;


